# **Análise: Dados eleitorais**
Grupo: Bianca Muniz, Jamile Santana, Jessica Avelar, Kaluan Bernardo e Thiago Araújo

In [1]:
# Importando as bibliotecas
import pandas as pd #para abrir e manipular as bases
import statistics #para o cálculo da moda
!pip install altair #instalando a biblioteca altair
import altair as alt #para as visualizações gráficas

Requirement already satisfied: altair in /usr/local/lib/python3.7/dist-packages (4.1.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from altair) (0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from altair) (2.11.3)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.7/dist-packages (from altair) (2.6.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from altair) (1.19.5)
Requirement already satisfied: toolz in /usr/local/lib/python3.7/dist-packages (from altair) (0.11.1)
Requirement already satisfied: pandas>=0.18 in /usr/local/lib/python3.7/dist-packages (from altair) (1.1.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.18->altair) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.18->altair) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.18->altair) (1.15.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->altair) (2.0.1)

In [5]:
# Lendo os arquivos com o pandas (o link abre a planilha já filtrada pelo estado do RJ)
despesas_rj = pd.read_csv("https://raw.githubusercontent.com/biamuniz/mjda_insper/main/inferencia_causal/atividade%201/dados/despesas_rio.csv", sep=";")
prefeitos_rj = pd.read_csv("https://raw.githubusercontent.com/biamuniz/mjda_insper/main/inferencia_causal/atividade%201/dados/prefeitos_rio.csv", sep=";")
resultados_rj = pd.read_csv("https://raw.githubusercontent.com/biamuniz/mjda_insper/main/inferencia_causal/atividade%201/dados/resultados_rio.csv", sep=";")

Qual o valor total, máximo, mínimo, média e mediana de despesas por município?

In [6]:
despesas_rj

        Unnamed: 0  ...   valor
0           895772  ...   320.0
1           895773  ...   320.0
2           895774  ...   320.0
3           895775  ...  1430.0
4           895776  ...   182.6
...            ...  ...     ...
103915      999687  ...    90.0
103916      999688  ...   300.0
103917      999689  ...   300.0
103918      999690  ...   300.0
103919      999691  ...   500.0

[103920 rows x 18 columns]

In [7]:
# Para responder à pergunta, fizemos uma tabela dinâmica
variaveis = despesas_rj.columns.difference(set(['muni']).union(set([])).union(set({'valor'}))) # Acho que selecionei as colunas que eu quero olhar (município e valor da despesa)
variaveis2 = despesas_rj.drop(variaveis, axis=1) # Não sei o que significa
# Fazendo a tabela dinâmica
pivot_table = variaveis2.pivot_table(
    index=['muni'],
    values=['valor'],
    aggfunc={'valor': ['sum', 'mean', 'min', 'max', 'median', 'count']}
)


# Reset the column name and the indexes
tabela_municipio = pivot_table.reset_index()

In [8]:
tabela_municipio

                  muni valor
                       count      max         mean  median   min         sum
0       ANGRA DOS REIS  2775  75000.0   677.152411  270.00  0.10  1879097.94
1              APERIBÉ   156  12000.0   643.633654  200.00  6.95   100406.85
2             ARARUAMA  2418  53000.0   559.114657  242.00  0.07  1351939.24
3                AREAL   103  17694.0  1375.508738  700.00  6.45   141677.40
4   ARMAÇÃO DOS BÚZIOS  1463  38000.0   632.015277  350.00  0.35   924638.35
..                 ...   ...      ...          ...     ...   ...         ...
87           TRÊS RIOS   928  33000.0   958.120259  300.00  0.35   889135.60
88             VALENÇA   980  15000.0   516.720643  250.00  1.00   506386.23
89           VARRE-SAI    92  21439.0  1219.088913  116.25  0.35   112156.18
90           VASSOURAS   639  25000.0   669.433881   91.50  0.35   427768.25
91       VOLTA REDONDA  1824  65127.0   761.379320  127.30  0.35  1388755.88

[92 rows x 7 columns]

In [13]:
despesas_rj['valor'] = despesas_rj['valor'].astype('int')

In [14]:
# Despesas por partido
unused_columns = despesas_rj.columns.difference(set(['partido']).union(set([])).union(set({'valor'})))
tmp_df = despesas_rj.drop(unused_columns, axis=1)
pivot_table = tmp_df.pivot_table(
    index=['partido'],
    values=['valor'],
    aggfunc={'valor': ['sum', 'mean', 'min', 'max', 'median', 'count']}
)


# Reset the column name and the indexes
despesa_partido = pivot_table.reset_index()

In [15]:
despesa_partido

          partido   valor
                    count        max         mean median    min         sum
0          AVANTE  2255.0   150000.0  1189.732151  300.0    0.0   2682846.0
1       CIDADANIA  2900.0    67000.0  1090.722069  320.0    0.0   3163094.0
2              DC   422.0    10000.0   628.898104  194.0    0.0    265395.0
3             DEM  8713.0  1450000.0  1757.897165  197.0    0.0  15316558.0
4             MDB  6928.0   875000.0   952.706986  300.0    0.0   6600354.0
5            NOVO   336.0    70000.0  3526.791667  600.0    1.0   1185002.0
6        PATRIOTA   542.0    35000.0   924.446494  200.0    0.0    501050.0
7         PC do B   671.0    37000.0   950.940387  214.0    0.0    638081.0
8             PDT  8146.0   750000.0  2013.332310  250.0    0.0  16400605.0
9              PL  9126.0   100000.0   936.509095  267.0    0.0   8546582.0
10            PMB  1134.0   120000.0   652.054674  100.0    0.0    739430.0
11            PMN   136.0    12952.0   504.117647   53.5    2.0     68560.0
12           PODE   807.0    50000.0  1149.986369  250.0    0.0    928039.0
13             PP  7356.0   100000.0   822.750000  300.0    0.0   6052149.0
14           PROS  2103.0   355000.0  1344.377556  150.0    0.0   2827226.0
15           PRTB  1154.0    38000.0   564.366551  225.0    0.0    651279.0
16            PSB  1422.0   100000.0  1180.741913  380.0    0.0   1679015.0
17            PSC  7560.0   800000.0  1030.265079  250.0    0.0   7788804.0
18            PSD  8403.0    60000.0   625.621207  200.0    0.0   5257095.0
19           PSDB  2820.0    97500.0   945.958865  200.0    0.0   2667604.0
20            PSL  4807.0   700000.0  1895.983774  365.0    0.0   9113994.0
21           PSOL  1922.0    53000.0  1417.875650  400.0    0.0   2725157.0
22           PSTU   105.0     8000.0   776.600000  200.0    1.0     81543.0
23             PT  8495.0   850000.0  1333.212242  270.0    0.0  11325638.0
24            PTB  1641.0    45000.0  1128.009750  350.0    0.0   1851064.0
25            PTC  1017.0    80000.0   915.326450  290.0    0.0    930887.0
26             PV   237.0    20000.0  1244.632911  350.0    0.0    294978.0
27           REDE   395.0   104553.0  5541.954430  900.0    0.0   2189072.0
28   REPUBLICANOS  7541.0   500000.0  1483.319984  300.0    0.0  11185716.0
29  SOLIDARIEDADE  4823.0   140000.0   837.563135  250.0    0.0   4039567.0
30             UP     3.0      989.0   533.000000  500.0  110.0      1599.0

In [16]:
despesa_partido.to_csv("despesas_partido.csv", sep=';', encoding='utf-8')